class S {
  static String lang = 'tr';

  static const Map<String, Map<String, String>> t = {
    'tr': {
      'app_title': 'Yönetim Paneli',
      'login_title': 'Yönetici Girişi',
      'username': 'Kullanıcı Adı',
      'password': 'Şifre',
      'login': 'Giriş Yap',
      'login_error': 'Giriş başarısız, bilgileri kontrol edin',
      'orders': 'Siparişler',
      'today': 'Bugün',
      'yesterday': 'Dün',
      'all': 'Tümü',
      'new_order': 'Yeni Sipariş!',
      'view': 'Görüntüle',
      'edit': 'Düzenle',
      'delete': 'Sil',
      'call': 'Ara',
      'copied': 'Numara kopyalandı',
      'name': 'Ad Soyad',
      'phone': 'Telefon',
      'address': 'Adres',
      'items': 'Ürünler',
      'price': 'Fiyat',
      'status': 'Durum',
      'notes': 'Notlar',
      'date': 'Tarih',
      'save': 'Kaydet',
      'cancel': 'Vazgeç',
      'add_item': 'Ürün Ekle',
      'item_name': 'Ürün adı',
      'count': 'Adet',
      'delete_confirm': 'Bu sipariş silinsin mi?',
      'yes_delete': 'Evet, Sil',
      'settings': 'Ayarlar',
      'sheet_url': 'Google Apps Script URL',
      'save_login': 'Kaydet ve Bağlan',
      'dark_mode': 'Koyu Tema',
      'language': 'Dil',
      'notif_sound': 'Bildirim Sesi',
      'sound_default': 'Varsayılan',
      'sound_alarm': 'Alarm',
      'sound_silent': 'Sessiz',
      'sound_custom': 'Özel ses (telefondan seç)',
      'pick_sound': 'Ses dosyası seç',
      'vibrate': 'Titreşim',
      'banner': 'Ekran üstü banner',
      'logout': 'Çıkış Yap',
      'connected': 'Bağlantı başarılı',
      'empty': 'Sipariş bulunamadı',
      'refresh': 'Yenile',
      'add': 'Ekle',
    },
    'ar': {
      'app_title': 'لوحة الإدارة',
      'login_title': 'تسجيل دخول المدير',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'login': 'دخول',
      'login_error': 'فشل الدخول، تحقق من البيانات',
      'orders': 'الطلبات',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'all': 'الكل',
      'new_order': 'طلب جديد!',
      'view': 'عرض',
      'edit': 'تعديل',
      'delete': 'حذف',
      'call': 'اتصال',
      'copied': 'تم نسخ الرقم',
      'name': 'الاسم',
      'phone': 'الهاتف',
      'address': 'العنوان',
      'items': 'المنتجات',
      'price': 'السعر',
      'status': 'الحالة',
      'notes': 'ملاحظات',
      'date': 'التاريخ',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'add_item': 'إضافة منتج',
      'item_name': 'اسم المنتج',
      'count': 'العدد',
      'delete_confirm': 'هل تريد حذف هذا الطلب؟',
      'yes_delete': 'نعم، احذف',
      'settings': 'الإعدادات',
      'sheet_url': 'رابط Google Apps Script',
      'save_login': 'حفظ واتصال',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'notif_sound': 'صوت الإشعار',
      'sound_default': 'افتراضي',
      'sound_alarm': 'منبه',
      'sound_silent': 'صامت',
      'sound_custom': 'صوت خاص (من الهاتف)',
      'pick_sound': 'اختيار ملف صوت',
      'vibrate': 'الاهتزاز',
      'banner': 'بانر أعلى الشاشة',
      'logout': 'تسجيل الخروج',
      'connected': 'تم الاتصال بنجاح',
      'empty': 'لا توجد طلبات',
      'refresh': 'تحديث',
      'add': 'إضافة',
    }
  };

  static String get(String k) => t[lang]?[k] ?? k;
}